### Script Generated by Control Surface Studio for Python 3 (resorted to default: no)
from .octatrack_ableton_sync import octatrack_ableton_sync

def create_instance(c_instance):
	return octatrack_ableton_sync(c_instance)